# Generated by Django 5.0 on 2026-03-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='channel_posts/'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
