# Generated by Django 5.0 on 2026-03-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_globalchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalchatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
        migrations.AddField(
            model_name='globalchatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('join', 'User Joined'), ('leave', 'User Left'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='globalchatmessage',
            name='message',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
