# Generated by Django 5.0 on 2026-03-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_globalchatmessage_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalchatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chatglobal/'),
        ),
    ]
